module: AMglTF
author: hyunjun529
author_url: https://github.com/hyunjun529/ARKit-Metal-glTF-example
github_url: https://github.com/hyunjun529/ARKit-Metal-glTF-example

min_acl: internal

source_directory: ./AMglTF

exclude: "./AMglTF/AMglTF Shared/Utility/glTF Importer/*"

output: ./docs
